version: 2.1
jobs:
  build:
    docker:
      - image: cimg/php:8.1.9-node
      - image: cimg/mysql:8.0
        environment:
          MYSQL_DATABASE: finderspace
          MYSQL_USER: default
          MYSQL_PASSWORD: secret
    environment:
      APP_ENV: testing
      DB_CONNECTION: mysql
      DB_HOST: localhost
      DB_PORT: 3306
      DB_DATABASE: finderspace
      DB_USERNAME: default
      DB_PASSWORD: secret
    steps:
      - checkout
      - restore_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
      - restore_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}
      - run:
          name: npm ci
          command: |
            if [ ! -d node_modules ]; then
              npm ci
            fi 
      - save_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm run build
      - run:
          name: get ready for mysql
          command: |
            sudo apt-get update
            sudo docker-php-ext-install pdo_mysql
            dockerize -wait tcp://localhost:3306 -timeout 2m
      - run:
          name: php test
          command: vendor/bin/phpunit