version: 2.1
jobs:
  build:
    docker:
      - image: cimg/php:8.1.9-node
    steps:
      - checkout
      - run: composer install -n --prefer-dist
      - run: npm ci
      - run: npm run build
      - run:
          name: php test
          command: vendor/bin/phpunit